### ISSUE TITLE
Support Dapp name in dot-connect

### ISSUE THREAD

**Issue by Tbaut** [tien/dot-connect#154]
I thought about doing a PR, then I realize the change should be made first reactive-dot.. so I thought it may take me a while to figure out :sweat_smile: 
In any case, I'll use Dot-connect in Multix because it's simply the best out there, and for the tests, I need to have the Dapp pass its name to the extension. This wasn't possible due to papi before, now this has changed and since v1.6 and this https://github.com/polkadot-api/polkadot-api/pull/791 `connectInjectedExtension` accepts an optional name for the Dapp. 

Would it be possible to make this change and add an optional dapp name in the dotconnect config and subsequently pass this to `connectInjectedExtension` ?

**Comment by tien** [comment]
Should be resolved by tien/reactive-dot#260

**Comment by Tbaut** [comment]
Amazing, thank you so much, looking forward to it!

**Comment by Tbaut** [comment]
Amazing, thank you so much, I'll pull this version today :pray:
