### ISSUE TITLE
Uncaught Error: Extension unavailable, ping failed

### ISSUE THREAD

**Issue by Tbaut** [tien/dot-connect#175]
I caught this while testing all the scenarii.
When you click on connect for pjs-extension for instance, but the user rejects the auth request, ~~the whole dot-connect modal crashes/disappears~~ and unhandled exception is fired.

![image](https://github.com/user-attachments/assets/8151d527-6f10-40ae-b64a-63d7cc689661)

Instead, it'd be great to catch the error, show it in the console, and show the "connect" button again.

**Comment by tien** [comment]
@Tbaut thanks for reporting the issue. I've tried to reproduce this and was unable to get the modal to crash. Can you share a reproduction link if possible?

**Comment by Tbaut** [comment]
My bad, it's not crashing when run live, it's only my test instance that is stopping abruptly, because of an uncaught error.
As for the reproduction of the uncaught error, in case this is helpful, it's happening on https://delegit.xyz for instance, when you click on "connect" for Polkadot-js, but then "reject" the connection on the popup.

**Comment by Tbaut** [comment]
Thank you so much, the latest release solved it well :pray:
