### ISSUE TITLE
Export `wallets`?

### ISSUE THREAD

**Issue by mutantcornholio** [tien/dot-connect#201]
Hi!

Can I ask you to export [these](https://github.com/tien/dot-connect/tree/main/packages/dot-connect/src/wallets)? 
My usecase is, I'd like to indicate the wallet, from which the accounts come from; currently I only have ids like `subwallet-js` and `talisman`.  

Having a logo / display name of the supported wallets would be sweet.

**Comment by tien** [comment]
Hey @mutantcornholio, unfortunately the wallet interface there are not meant to be stable nor public (they are not that great tbh 😅).

Beside `id`, you can already get the wallet display name from the wallet interface returned by ReactiveDOT.

As for the logos it might be best either copy them to your project if you really want them to be the same, or get it elsewhere.

**Comment by mutantcornholio** [comment]
Is there any particular reason why making this data available to devs would be a bad idea?  
It's already shipped with the package and my usecase doesn't strike me as something out of the ordinary.  

List of supported wallets (at least the injected ones) is not defined anywhere on the application side, so copying the mapping to name / logo will probably lead to misalignment in future updates, if dot-connect will support more wallets at some point.  

If the interface for getting the wallet data is not good enough to be public, maybe export some getter, like
```ts
function getWalletMeta(wallet: Wallet): { displayName: string; logo: string };
```

> Beside `id`, you can already get the wallet display name from the wallet interface returned by ReactiveDOT.

That's `wallet.name`, right? It'll return `subwallet-js` and `talisman`, not `SubWallet` and `Talisman`.

**Comment by tien** [comment]
Yeah make sense that it could be useful to get the logo & name used by dot-connect. I'm not 100% convinced that the assets should be owned by dot-connect though, so will mark the `getWalletMetadata` function as `experimental`.
