### ISSUE TITLE
Can't connect with walletconnect

### ISSUE THREAD

**Issue by Tbaut** [tien/dot-connect#229]
I can't connect any account using walletconnect I tried on https://dotconnect.dev, but also on https://tbaut-bump-wc.delegit.pages.dev

FWIW, I've made sure to setup the domains allow list well on https://cloud.reown.com so this shouldn't be an issue for Delegit.
![image](https://github.com/user-attachments/assets/8b28ae96-e521-4ba7-bef2-e8ccf17ef888)

What happens:
- Dotconnect shows the QR code
- I scan it with the latest version of Nova wallet
- Nova prompt me to accept the connection, I allow
- nothing changes on the Dapp side, and Nova doesn't say that we're connected either
- no error in the console

**Comment by Susankaten** [comment]
> I can't connect any account using walletconnect I tried on https://dotconnect.dev, but also on https://tbaut-bump-wc.delegit.pages.dev
> 
> FWIW, I've made sure to setup the domains allow list well on https://cloud.reown.com so this shouldn't be an issue for Delegit. ![image](https://private-user-images.githubusercontent.com/33178835/392433736-8b28ae96-e521-4ba7-bef2-e8ccf17ef888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjUwNTMsIm5iZiI6MTczMzMyNDc1MywicGF0aCI6Ii8zMzE3ODgzNS8zOTI0MzM3MzYtOGIyOGFlOTYtZTUyMS00YmE3LWJlZjItZThjY2YxN2VmODg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE1MDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZDAxNTE1MzE0OTNkOTk5NGE5OTY1NzUxMjE1ZTI0NzkwMTY2NjhiNDU4NmVjYzJlYTk4YjAwZDYyMTkxNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c7Ci7bhHt7dgo00OaNg1c36o5UlULKiLbkgOiWFmheM)
> 
> What happens:
> 
> * Dotconnect shows the QR code
> * I scan it with the latest version of Nova wallet
> * Nova prompt me to accept the connection, I allow
> * nothing changes on the Dapp side, and Nova doesn't say that we're connected either
> * no error in the console

Hello @Tbaut 
You are experiencing the transcript error,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID NO176392
Please see the link below to our dedicated support line:
[Wallet Connect DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by tien** [comment]
Thanks for the report, I'll take a look!

**Comment by tien** [comment]
@Tbaut I've just give it a quick check, and it's working ok for me on https://dotconnect.dev/

Could be an issue with Nova Wallet, cuz I've had some difficulty there before.

**Comment by Tbaut** [comment]
Thank you, that was it, killed the app, relaunched, it worked eventually :pray:

**Comment by tien** [comment]
@Tbaut maybe someone from Nova can be tagged here? I've had this issue for longer than I would like to remember.

**Comment by Tbaut** [comment]
@Leemo94 I am sure this is something you get a lot of reports about. Can you confirm that this is known to the team, and maybe you can link an issue here or a PR so that we can track it too?
