### ISSUE TITLE
WalletConnect connection requesting several chains, answers with duplicated accounts

### ISSUE THREAD

**Issue by Tbaut** [tien/dot-connect#230]
Here's my wallet config, requesting polkadot, kusama and westend:
```ts
export const config = {
  chains: {},
  wallets: [
    new InjectedWalletProvider({ originName: 'Delegit' }),
    new WalletConnect({
      projectId: 'f7a61cf7fe70a61e728f1dd5d53e9cea',
      providerOptions: {
        metadata: {
          name: 'Delegit',
          description: 'Polkadot delegation made easy',
          url: 'https://delegit.xyz',
          icons: [
            'https://github.com/user-attachments/assets/293eee36-0443-4299-a426-fc56e58af012',
          ],
        },
      },
      chainIds: [
        // https://github.com/ChainAgnostic/CAIPs/blob/main/CAIPs/caip-13.md
        'polkadot:91b171bb158e2d3848fa23a9f1c25182', // Polkadot
        'polkadot:b0a8d493285c2df73290dfb7e61f870f', // Kusama
        'polkadot:e143f23803ac50e8f6f8e62695d1ce9e', // Westend
      ],
    }),
  ],
} satisfies Config
```

The `useAccounts` from `import { useAccounts } from '@reactive-dot/react'` then gives me 3 duplicated accounts, instead of 1 expected.

**Comment by tien** [comment]
For this, if you are using ReactiveDOT for querying as well, doing `useAccounts({ chainId: "polkadot" })` will filter accounts by their target chain (also work by setting chain ID via context).

**Comment by Tbaut** [comment]
Fair enough, I'm filtering them now. 1 thing that could be helpful is to know where it comes from.
Like I have now 2 times the same account, once from Talisman, once from WalletConnect, and I'd love to show it in the app, but the metadata don't reflect it.

**Comment by tien** [comment]
@Tbaut you can use `account.wallet.id` which is guarantee to be stable.

**Comment by Tbaut** [comment]
The thing is, an id of type number doesn't tell me if it comes from Pjs or from Talisman. This is a valuable info to display.
I can open a separate issue, as it's not related to this one.

**Comment by Tbaut** [comment]
Sorry I had checked only quickly. There's no id for the wallet, but a name, that seems totally good enough:
![image](https://github.com/user-attachments/assets/525b3c4d-5b06-4870-b1e2-92312d0a4137)

**Comment by tien** [comment]
@Tbaut awesome! Though to be even safer you can use the ID, I believe it doesn't show up in the console because it's a getter property.
