### ISSUE TITLE
Plans to support Ledger and Polkadot Vault?

### ISSUE THREAD

**Issue by laurogripa** [tien/dot-connect#41]
Hey!

Congrats on the initiative, reminds me of [web3modal](https://github.com/WalletConnect/web3modal).
I've been dreaming of something like this for ages, very promising!

Am I correct in saying the current version doesn't support Ledger and PV? If not, are there any plans to support it in the future?

**Comment by tien** [comment]
Hey, it definitely can! Just need to be added as one of the supported wallets [here](https://github.com/tien/reactive-dot/tree/main/packages/core/src/wallets). Implementation side on `dot-connect` would just be to add UI around it. Can't believe I missed ledger, will take a look at it this week 💪. (Also PV 2)

**Comment by tien** [comment]
Updates on this:

The problem itself isn’t particularly hard to solve. The challenge lies in creating a structure that makes sense. Both Ledger and PV will need two things:

- A custom UI
- Storage for connected accounts

These are non-agnostic requirements beyond what ReactiveDOT typically provides.

I’m currently considering options, but it’s likely this will be incorporated into `dot-connect` instead, where custom UI and storage logic fit better.

**Comment by laurogripa** [comment]
@tien

Thanks for the update!

I'm looking forward to it, let me know if I can help. 

I'm considering re-implementing many things on the [Kusama Society website](https://github.com/KappaSigmaMu/kappasigmamu.github.io/) eventually, mainly replacing PolkadotJS API with PAPI but also using `reactive-dot` and `dot-connect` as a base for the wallet/account selector instead of `talisman-connect` (which seems unmaintained lately).

I'll let you know if I can find the time to do it in the next months. If it makes sense, maybe I can be a sort of beta-tester and contribute to your repos as well!

**Comment by tien** [comment]
That's great to hear, @laurogripa!

And yes, helps with testing and contributions are always very much welcomed 🙏

**Comment by tien** [comment]
Splitting this issue into #102 & #103.
